### ISSUE TITLE
Asynchronous (distributed) Event Model?

### ISSUE THREAD

**Issue by jrmlhermitte** [CFN-softbio/SciStreams#14]
Before discussing the topic, I'll give a brief summary of what I mean by asynchronous or distributed (which could be interpreted different ways):
```python
# start a connection to scheduler
from distributed import Client
# the argument here should be ip:port of running scheduler
# (leave blank and distributed will automatically make one for testing)
client = Client() 
# run a computation on a cluster of function multiplybytwo on data data
def multiplybytwo(data):
    return 2*data
future = client.submit(multiplybytwo, 4)
# this function immediately returns a future
# now let's run a second computation that involves the previous result:
def adder(data1, data2):
    return data1 + data2
future2 = client.submit(adder, future, 3)
# now obtain the result, this will block until the result is received
myfinal_result = future2.result()
```
Normally, when running analysis, we'll have an event loop that will send a series of chained computations to the cluster, where the final function call performs a saving operation somewhere. **At no moment** will it block for a result. (i.e. we would **never** call `future2.result()`. The computation that would trigger `future2` would contain the saving and not contain a useful output).

We've been using our own data structures for analysis, but we'd like our output to adhere to the event model so that it may be saved or further processed via various Callbacks. We have run into the following problem where some of our results (including the `start` which can contain metadata generated on the cluster) are `Future`s. Say you have a series of documents:
```python
('start', future_1)
('descriptor', future_2)
('descriptor', future_3)
('event', future_4)
('stop', future_5)
```
Further processing could only be done by the simplest of callbacks but no more. For example, if we wanted a callback that would generate an xml file for each event with the event data **and** its metadata contained in the start, we would have to first call for the result of all descriptors that came through and search for the corresponding one. Once the correct descriptor is found, we would call for the result of all buffered starts and search for the correct start (which as of now should only be one). This seems messy. It could be avoided.

One solution is to buffer all the computed starts and descriptors as they go. However, if your start or descriptor is the result of a longer chain of analyses, you may not want to block on that, especially if for an event it was not the descriptor you needed. Another option is to have the search be done on the cluster, but now you need to save a future list of all starts and descriptors and send it to the cluster. Even worse, this list can no longer be garbage collected since in principle you don't know what's in it. I have thought of other solutions (like time stamps) but they all seem messy to me.

## Possible Solution
I would propose that the syntax of how documents are yielded be extended to externalizing the information of the tree structure of the contents from the data itself. For example
```python
    # docname, (parent_uid, self_uid, doc)
    yield "start", (None, start_uid, start)
    # it's a tree structure so we need parent_uid, and self_uid
    yield "descriptor", (start_uid, descriptor_uid, descriptor)
    yield "event", (descriptor_uid, event_uid, event)
    yield "stop", (start_uid, stop_uid, stop)
```

We've already implemented this and it works just fine for us. See this [line](https://github.com/CFN-softbio/SciStreams/blob/event-stream-async/SciStreams/callbacks/core.py#L94) for example. I'm happy to discuss with examples. I apologize that the code is quite messy.

I would like to hear your thoughts about moving quantities in the event stream to remote computations.

**Comment by danielballan** [comment]
I see the problem. In the spirit of brainstorming other (not necessarily better) possibilities, what would be the advantages and disadvantages of this scheme:

```
yield ('start', event)
```

where `event` is

```
{'uid': '...'
 'descriptor': '...'
 'time': ...,
 'data': future_1,
 'timestamps': ...}
```

**Comment by jrmlhermitte** [comment]
That would work and actually sounds much simpler. It still wouldn't solve `start` however, unless if `start`'s metadata were in its own field, such as:
```
{'uid' : '...',
'attributes' : future_a,
'time' : ...}
```
where `future_a` would now be a `Future` for the metadata. Since the attributes of `start` are really user defined, we could just do this right now without breaking anything. The only issue is that this will no longer be searchable (or easy to do so).

**Comment by jrmlhermitte** [comment]
It should be fine:
```python
('start', {'uid', '...', 'attributes': future_1, 'time' : '...')
('descriptor', {'uid', '...', 'run_start' : '...', 'data_keys' : future_2, 'time' : ...})
('event', {'uid', '...', 'descriptor' : '...', 'data' : future_3, 'time' : ..., 'timestamps' : ...})
('stop', {'uid', '...','run_start' : '...', 'time' : ...})
```
The only change is that when the stream comes in my analysis pipeline, metadata is moved to `attributes`. This is still conforming with the event model structure. When the stream comes out, `attributes` is moved back to metadata. One could imagine pipelines running more complex operations (such as the number of events coming out depending on a future) so it probably makes sense not to change the event model at all.

One could imagine that the process dealing with these streams just have an extra check `if 'attributes' in doc and isinstance(doc['attributes'], Future)` if `Futures` are permitted to pass through this stream (note it may not always be possible to handle `Future`s)


(Right now, it's working in the distributed regime with the overly complicated structure I described before, but I'll change it soon. Thanks for the input!)
